### ISSUE TITLE
App Logs: This app doesn't have any navigation items 

### ISSUE THREAD

**Issue by RyanSchierholz** [mlockett/ApexLogger#4]
When launching the App Logs app, there are no tabs. Salesforce says: "Well, this is awkward. This app doesn't have any navigation items, or you can't access them. [Learn More](https://payactiv--staging.sandbox.lightning.force.com/HelpAndTrainingDoor?version=2&resource=https%3A%2F%2Fhelp.salesforce.com%2FarticleView%3Fid%3Duser_userdisplay_tabs_lex.htm) about how to personalize your navigation bar, or ask your admin for help."
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/10843e5e-9210-42ad-bd9a-be6164032d7e">

**Comment by RyanSchierholz** [comment]
when adding a new page, I see there likely are others already available, but not visible: 
Lot List
Log Reader
etc
<img width="995" alt="Screenshot 2024-12-02 at 1 48 50 PM" src="https://github.com/user-attachments/assets/965306d3-6c7a-445d-82d1-9dfbd5192c6a">

**Comment by mlockett** [comment]
Hi Ryan.

Did you assign yourself the AppLogReader permission set?

**Comment by RyanSchierholz** [comment]
Yes, the app is available, but there are no tabs 'available' or 'visible' in the PS. If you don't mind, I'm practicing my github, so I can prepare an update?

**Comment by mlockett** [comment]
Thanks Ryan! I accepted your PR.
